name: CI

on:
  release:
    types:
      - published
      - prereleased

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: yarn
        run: yarn

      # Runs a set of commands using the runners shell
      - name: publish extentions
        run: npx publish
        with:
          args: "-p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
